In [3]:
import pandas as pd

samples = pd.read_csv("../data/s_MTBLS2550.txt", sep="\t")

print(samples.shape)
samples.head()

(166, 43)

,Source Name,Characteristics[Organism],Term Source REF,Term Accession Number,Characteristics[Organism part],Term Source REF.1,Term Accession Number.1,Characteristics[Variant],Term Source REF.2,Term Accession Number.2,...,Term Accession Number.9,Factor Value[HER2 status],Term Source REF.10,Term Accession Number.10,Factor Value[Intercurrent tumors],Term Source REF.11,Term Accession Number.11,Factor Value[Breed],Term Source REF.12,Term Accession Number.12
0,16K-008,Canis lupus familiaris,NCBITAXON,http://purl.obolibrary.org/obo/NCBITaxon_9615,urine,BTO,http://purl.obolibrary.org/obo/BTO_0001419,Chihuahua,NCIT,http://purl.obolibrary.org/obo/NCIT_C53929,...,http://purl.obolibrary.org/obo/NCIT_C15492,Positive,NCIT,http://purl.obolibrary.org/obo/NCIT_C68748,simple carcinoma (grade 1),NaN,NaN,Chihuahua,NaN,NaN
1,16K-021,Canis lupus familiaris,NCBITAXON,http://purl.obolibrary.org/obo/NCBITaxon_9615,urine,BTO,http://purl.obolibrary.org/obo/BTO_0001419,Maltese,NCIT,http://purl.obolibrary.org/obo/NCIT_C53936,...,http://purl.obolibrary.org/obo/NCIT_C126101,Not Available,NCIT,http://purl.obolibrary.org/obo/NCIT_C126101,NaN,NaN,NaN,Maltese,NaN,NaN
2,16K-030,Canis lupus familiaris,NCBITAXON,http://purl.obolibrary.org/obo/NCBITaxon_9615,urine,BTO,http://purl.obolibrary.org/obo/BTO_0001419,Maltese,NCIT,http://purl.obolibrary.org/obo/NCIT_C53936,...,http://purl.obolibrary.org/obo/NCIT_C126101,Not Available,NCIT,http://purl.obolibrary.org/obo/NCIT_C126101,NaN,NaN,NaN,Maltese,NaN,NaN
3,16K-072,Canis lupus familiaris,NCBITAXON,http://purl.obolibrary.org/obo/NCBITaxon_9615,urine,BTO,http://purl.obolibrary.org/obo/BTO_0001419,Mixed Breed,NCIT,http://purl.obolibrary.org/obo/NCIT_C53951,...,http://purl.obolibrary.org/obo/NCIT_C15492,Positive,NCIT,http://purl.obolibrary.org/obo/NCIT_C68748,NaN,NaN,NaN,Mixed Breed,NaN,NaN
4,16K-077,Canis lupus familiaris,NCBITAXON,http://purl.obolibrary.org/obo/NCBITaxon_9615,urine,BTO,http://purl.obolibrary.org/obo/BTO_0001419,Beagle,NCIT,http://purl.obolibrary.org/obo/NCIT_C53897,...,http://purl.obolibrary.org/obo/NCIT_C15493,Negative,NCIT,http://purl.obolibrary.org/obo/NCIT_C68749,NaN,NaN,NaN,Beagle,NaN,NaN

In [4]:
samples.columns

Index(['Source Name', 'Characteristics[Organism]', 'Term Source REF',
       'Term Accession Number', 'Characteristics[Organism part]',
       'Term Source REF.1', 'Term Accession Number.1',
       'Characteristics[Variant]', 'Term Source REF.2',
       'Term Accession Number.2', 'Characteristics[Sample type]',
       'Term Source REF.3', 'Term Accession Number.3', 'Protocol REF',
       'Sample Name', 'Factor Value[Sex]', 'Term Source REF.4',
       'Term Accession Number.4', 'Factor Value[Tumor state]',
       'Term Source REF.5', 'Term Accession Number.5',
       'Factor Value[Tumor grade]', 'Term Source REF.6',
       'Term Accession Number.6', 'Factor Value[Age]', 'Unit',
       'Term Source REF.7', 'Term Accession Number.7',
       'Factor Value[Neutral Status]', 'Term Source REF.8',
       'Term Accession Number.8', 'Factor Value[ER status]',
       'Term Source REF.9', 'Term Accession Number.9',
       'Factor Value[HER2 status]', 'Term Source REF.10',
       'Term Accession Number.10', 'Factor Value[Intercurrent tumors]',
       'Term Source REF.11', 'Term Accession Number.11', 'Factor Value[Breed]',
       'Term Source REF.12', 'Term Accession Number.12'],
      dtype='str')

In [6]:
metabolites = pd.read_csv(
    "../data/m_MTBLS2550_NMR_CrAdj_metabolite_profiling_v2_maf.tsv",
    sep="\t"
)

print(metabolites.shape)
metabolites.head()

(56, 184)

,database_identifier,chemical_formula,smiles,inchi,metabolite_identification,chemical_shift,multiplicity,taxid,species,database,...,N-46_CrAdj,N-47_CrAdj,N-48_CrAdj,N-49_CrAdj,N-5_CrAdj,N-50_CrAdj,N-6_CrAdj,N-7_CrAdj,N-8_CrAdj,N-9_CrAdj
0,CHEBI:16797,C7H9N2O+,C[n+]1cccc(c1)C(N)=O,InChI=1S/C7H8N2O/c1-9-4-2-3-6(5-9)7(8)10/h2-5H...,1-Methylnicotinamide,"4.468(s), 8.172(m), 8.89(d), 8.97(d), 9.28(s)",NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,62.347629,61.097004,73.359667,44.949733,323.732306,60.390361,9.809516,28.084559,245.666184,1.664852
1,CHEBI:1148,C4H8O3,CCC(O)C(O)=O,"InChI=1S/C4H8O3/c1-2-3(5)4(6)7/h3,5H,2H2,1H3,(...",2-Hydroxybutyrate,"0.904 (t), 1.658 (m), 1.738 (m), 4.006(m)",NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,5.745055,3.118573,4.635981,3.139404,9.317327,6.499133,35.379473,59.429839,32.092595,7.451337
2,CHEBI:50129,C4H8O3,CC(C)(O)C(O)=O,"InChI=1S/C4H8O3/c1-4(2,7)3(5)6/h7H,1-2H3,(H,5,6)",2-Hydroxyisobutyrate,1.35(S),NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,7.970999,6.478522,8.207578,6.659892,16.081347,7.262524,7.853047,12.433092,12.205708,3.329704
3,CHEBI:48430,C6H10O3,CC(C)CC(=O)C(O)=O,"InChI=1S/C6H10O3/c1-4(2)3-5(7)6(8)9/h4H,3H2,1-...",2-Oxoisocaproate,"0.9(d), 2.60(d)",NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,NaN,0.202756,1.951370,1.106958,1.478230,1.114137,4.293362,4.124602,3.840589,0.539952
4,CHEBI:48526,C9H10O2,CC(C(O)=O)c1ccccc1,InChI=1S/C9H10O2/c1-7(9(10)11)8-5-3-2-4-6-8/h2...,2-Phenylpropionate,1.397 (d),NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,1.886752,1.071708,2.944794,NaN,4.031536,2.063217,10.679058,1.329697,5.813495,4.886565

In [7]:
metabolites.columns

Index(['database_identifier', 'chemical_formula', 'smiles', 'inchi',
       'metabolite_identification', 'chemical_shift', 'multiplicity', 'taxid',
       'species', 'database',
       ...
       'N-46_CrAdj', 'N-47_CrAdj', 'N-48_CrAdj', 'N-49_CrAdj', 'N-5_CrAdj',
       'N-50_CrAdj', 'N-6_CrAdj', 'N-7_CrAdj', 'N-8_CrAdj', 'N-9_CrAdj'],
      dtype='str', length=184)