## Carregamento da base de amostras

Nesta etapa, é realizada a leitura do conjunto de dados contendo informações relacionadas às amostras analisadas. Essa base reúne atributos clínicos e biológicos relevantes, como sexo, idade, estado tumoral e características associadas aos indivíduos estudados. Após o carregamento, são realizadas verificações iniciais da estrutura do conjunto de dados, incluindo dimensões e nomes das variáveis disponíveis.

In [56]:
import pandas as pd

samples = pd.read_csv("../data/s_MTBLS2550.txt", sep="\t")

print(samples.shape)
samples.head(1)

(166, 43)

,Source Name,Characteristics[Organism],Term Source REF,Term Accession Number,Characteristics[Organism part],Term Source REF.1,Term Accession Number.1,Characteristics[Variant],Term Source REF.2,Term Accession Number.2,...,Term Accession Number.9,Factor Value[HER2 status],Term Source REF.10,Term Accession Number.10,Factor Value[Intercurrent tumors],Term Source REF.11,Term Accession Number.11,Factor Value[Breed],Term Source REF.12,Term Accession Number.12
0,16K-008,Canis lupus familiaris,NCBITAXON,http://purl.obolibrary.org/obo/NCBITaxon_9615,urine,BTO,http://purl.obolibrary.org/obo/BTO_0001419,Chihuahua,NCIT,http://purl.obolibrary.org/obo/NCIT_C53929,...,http://purl.obolibrary.org/obo/NCIT_C15492,Positive,NCIT,http://purl.obolibrary.org/obo/NCIT_C68748,simple carcinoma (grade 1),NaN,NaN,Chihuahua,NaN,NaN

In [57]:
samples.columns

Index(['Source Name', 'Characteristics[Organism]', 'Term Source REF',
       'Term Accession Number', 'Characteristics[Organism part]',
       'Term Source REF.1', 'Term Accession Number.1',
       'Characteristics[Variant]', 'Term Source REF.2',
       'Term Accession Number.2', 'Characteristics[Sample type]',
       'Term Source REF.3', 'Term Accession Number.3', 'Protocol REF',
       'Sample Name', 'Factor Value[Sex]', 'Term Source REF.4',
       'Term Accession Number.4', 'Factor Value[Tumor state]',
       'Term Source REF.5', 'Term Accession Number.5',
       'Factor Value[Tumor grade]', 'Term Source REF.6',
       'Term Accession Number.6', 'Factor Value[Age]', 'Unit',
       'Term Source REF.7', 'Term Accession Number.7',
       'Factor Value[Neutral Status]', 'Term Source REF.8',
       'Term Accession Number.8', 'Factor Value[ER status]',
       'Term Source REF.9', 'Term Accession Number.9',
       'Factor Value[HER2 status]', 'Term Source REF.10',
       'Term Accession Number.10', 'Factor Value[Intercurrent tumors]',
       'Term Source REF.11', 'Term Accession Number.11', 'Factor Value[Breed]',
       'Term Source REF.12', 'Term Accession Number.12'],
      dtype='str')

## Carregamento dos dados metabolômicos

Após a exploração inicial das informações das amostras, realiza-se o carregamento da base metabolômica. Esse conjunto de dados contém medições relacionadas aos metabólitos identificados em cada amostra, representando informações importantes para a análise computacional e para a identificação de possíveis padrões associados ao câncer mamário canino.

In [58]:
metabolites = pd.read_csv(
    "../data/m_MTBLS2550_NMR_CrAdj_metabolite_profiling_v2_maf.tsv",
    sep="\t"
)

print(metabolites.shape)
metabolites.head()

(56, 184)

,database_identifier,chemical_formula,smiles,inchi,metabolite_identification,chemical_shift,multiplicity,taxid,species,database,...,N-46_CrAdj,N-47_CrAdj,N-48_CrAdj,N-49_CrAdj,N-5_CrAdj,N-50_CrAdj,N-6_CrAdj,N-7_CrAdj,N-8_CrAdj,N-9_CrAdj
0,CHEBI:16797,C7H9N2O+,C[n+]1cccc(c1)C(N)=O,InChI=1S/C7H8N2O/c1-9-4-2-3-6(5-9)7(8)10/h2-5H...,1-Methylnicotinamide,"4.468(s), 8.172(m), 8.89(d), 8.97(d), 9.28(s)",NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,62.347629,61.097004,73.359667,44.949733,323.732306,60.390361,9.809516,28.084559,245.666184,1.664852
1,CHEBI:1148,C4H8O3,CCC(O)C(O)=O,"InChI=1S/C4H8O3/c1-2-3(5)4(6)7/h3,5H,2H2,1H3,(...",2-Hydroxybutyrate,"0.904 (t), 1.658 (m), 1.738 (m), 4.006(m)",NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,5.745055,3.118573,4.635981,3.139404,9.317327,6.499133,35.379473,59.429839,32.092595,7.451337
2,CHEBI:50129,C4H8O3,CC(C)(O)C(O)=O,"InChI=1S/C4H8O3/c1-4(2,7)3(5)6/h7H,1-2H3,(H,5,6)",2-Hydroxyisobutyrate,1.35(S),NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,7.970999,6.478522,8.207578,6.659892,16.081347,7.262524,7.853047,12.433092,12.205708,3.329704
3,CHEBI:48430,C6H10O3,CC(C)CC(=O)C(O)=O,"InChI=1S/C6H10O3/c1-4(2)3-5(7)6(8)9/h4H,3H2,1-...",2-Oxoisocaproate,"0.9(d), 2.60(d)",NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,NaN,0.202756,1.951370,1.106958,1.478230,1.114137,4.293362,4.124602,3.840589,0.539952
4,CHEBI:48526,C9H10O2,CC(C(O)=O)c1ccccc1,InChI=1S/C9H10O2/c1-7(9(10)11)8-5-3-2-4-6-8/h2...,2-Phenylpropionate,1.397 (d),NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,1.886752,1.071708,2.944794,NaN,4.031536,2.063217,10.679058,1.329697,5.813495,4.886565

In [59]:
metabolites.columns.value_counts

<bound method IndexOpsMixin.value_counts of Index(['database_identifier', 'chemical_formula', 'smiles', 'inchi',
       'metabolite_identification', 'chemical_shift', 'multiplicity', 'taxid',
       'species', 'database',
       ...
       'N-46_CrAdj', 'N-47_CrAdj', 'N-48_CrAdj', 'N-49_CrAdj', 'N-5_CrAdj',
       'N-50_CrAdj', 'N-6_CrAdj', 'N-7_CrAdj', 'N-8_CrAdj', 'N-9_CrAdj'],
      dtype='str', length=184)>

## Seleção das variáveis clínicas relevantes

Nem todas as variáveis presentes na base original são necessárias para a construção do conjunto de dados final. Dessa forma, realiza-se uma etapa de filtragem, mantendo apenas os atributos considerados relevantes para a análise, incluindo características demográficas, informações tumorais e fatores clínicos potencialmente relacionados ao problema investigado.

In [60]:
cols_importantes = [
    'Source Name',
    'Factor Value[Sex]',
    'Factor Value[Tumor state]',
    'Factor Value[Tumor grade]',
    'Factor Value[Age]',
    'Factor Value[Neutral Status]',
    'Factor Value[ER status]',
    'Factor Value[HER2 status]',
    'Factor Value[Intercurrent tumors]',
    'Factor Value[Breed]'
]

In [61]:
samples_clean = samples[cols_importantes]

In [62]:
samples_clean.head(10)

,Source Name,Factor Value[Sex],Factor Value[Tumor state],Factor Value[Tumor grade],Factor Value[Age],Factor Value[Neutral Status],Factor Value[ER status],Factor Value[HER2 status],Factor Value[Intercurrent tumors],Factor Value[Breed]
0,16K-008,Female,Malignant,1.0,144,Intact,Positive,Positive,simple carcinoma (grade 1),Chihuahua
1,16K-021,Female,Malignant,1.0,192,Neutered,Not Available,Not Available,NaN,Maltese
2,16K-030,Female,Malignant,1.0,156,Intact,Not Available,Not Available,NaN,Maltese
3,16K-072,Female,Malignant,2.0,144,Intact,Positive,Positive,NaN,Mixed Breed
4,16K-077,Female,Malignant,3.0,168,Intact,Negative,Negative,NaN,Beagle
5,16K-096,Female,Malignant,2.0,144,Neutered,Positive,Positive,simple adenoma (1site),Yorkshire Terrier
6,16K-097,Female,Malignant,1.0,180,Neutered,Positive,Positive,NaN,Maltese
7,16K-099,Female,Malignant,1.0,144,Intact,Positive,Positive,Complex adenoma (1site),Maltese
8,16K-100,Female,Malignant,1.0,168,Intact,Positive,Positive,"Carcinoma in benign tumor (grade 1) (1site), B...",Cocker Spaniel
9,16K-105,Female,Malignant,3.0,144,Neutered,Negative,Positive,NaN,Mixed Breed

## Padronização dos nomes das variáveis

Após a seleção dos atributos relevantes, os nomes das colunas são padronizados com o objetivo de facilitar a manipulação computacional e melhorar a legibilidade do código. Essa etapa reduz inconsistências relacionadas a espaços, caracteres especiais e nomenclaturas extensas, tornando o processo de análise mais organizado.

In [63]:
samples_clean = samples_clean.rename(columns={
    'Source Name': 'sample_id',
    'Factor Value[Sex]': 'sex',
    'Factor Value[Tumor state]': 'tumor_state',
    'Factor Value[Tumor grade]': 'tumor_grade',
    'Factor Value[Age]': 'age',
    'Factor Value[Neutral Status]': 'neutered',
    'Factor Value[ER status]': 'er_status',
    'Factor Value[HER2 status]': 'her2_status',
    'Factor Value[Intercurrent tumors]': 'tumor_type',
    'Factor Value[Breed]': 'breed'
})

In [64]:
samples_clean.head(10)

,sample_id,sex,tumor_state,tumor_grade,age,neutered,er_status,her2_status,tumor_type,breed
0,16K-008,Female,Malignant,1.0,144,Intact,Positive,Positive,simple carcinoma (grade 1),Chihuahua
1,16K-021,Female,Malignant,1.0,192,Neutered,Not Available,Not Available,NaN,Maltese
2,16K-030,Female,Malignant,1.0,156,Intact,Not Available,Not Available,NaN,Maltese
3,16K-072,Female,Malignant,2.0,144,Intact,Positive,Positive,NaN,Mixed Breed
4,16K-077,Female,Malignant,3.0,168,Intact,Negative,Negative,NaN,Beagle
5,16K-096,Female,Malignant,2.0,144,Neutered,Positive,Positive,simple adenoma (1site),Yorkshire Terrier
6,16K-097,Female,Malignant,1.0,180,Neutered,Positive,Positive,NaN,Maltese
7,16K-099,Female,Malignant,1.0,144,Intact,Positive,Positive,Complex adenoma (1site),Maltese
8,16K-100,Female,Malignant,1.0,168,Intact,Positive,Positive,"Carcinoma in benign tumor (grade 1) (1site), B...",Cocker Spaniel
9,16K-105,Female,Malignant,3.0,144,Neutered,Negative,Positive,NaN,Mixed Breed

In [65]:
for col in metabolites.columns:
    print(col)

database_identifier
chemical_formula
smiles
inchi
metabolite_identification
chemical_shift
multiplicity
taxid
species
database
database_version
reliability
uri
search_engine
search_engine_score
smallmolecule_abundance_sub
smallmolecule_abundance_stdev_sub
smallmolecule_abundance_std_error_sub
16K-008_CrAdj
16K-021_CrAdj
16K-030_CrAdj
16K-031_CrAdj
16K-033_CrAdj
16K-070_CrAdj
16K-072_CrAdj
16K-074_CrAdj
16K-077_CrAdj
16K-092_CrAdj
16K-096_CrAdj
16K-097_CrAdj
16K-099_CrAdj
16K-100_CrAdj
16K-103_CrAdj
16K-105_CrAdj
16K-106_CrAdj
16K-107_CrAdj
16K-108_CrAdj
16K-112_CrAdj
16K-114_CrAdj
16K-116_CrAdj
16K-121_CrAdj
16K-129_CrAdj
16K-136_CrAdj
16K-142_CrAdj
16K-149_CrAdj
16K-153_CrAdj
16K-158_CrAdj
16K-162_CrAdj
16K-183_CrAdj
16K-188_CrAdj
16K-190_CrAdj
16K-197_CrAdj
16K-215_CrAdj
16K-217_CrAdj
16K-227_CrAdj
16K-231_CrAdj
16K-233_CrAdj
16K-234_CrAdj
16K-239_CrAdj
16K-242_CrAdj
16K-250_CrAdj
16K-252_CrAdj
16K-262_CrAdj
16K-263_CrAdj
16K-271_CrAdj
16K-276_CrAdj
16K-278_CrAdj
16K-283_CrAdj
16K-290_CrAdj
16K-292_CrAdj
16K-301_CrAdj
16K-306_CrAdj
16K-307_CrAdj
16K-308_CrAdj
16K-311_CrAdj
16K-317_CrAdj
16K-318_CrAdj
16K-319_CrAdj
16K-321_CrAdj
16K-336_CrAdj
16K-340_CrAdj
16K-348_CrAdj
16K-351_CrAdj
16K-353_CrAdj
16K-354_CrAdj
16K-360_CrAdj
16K-365_CrAdj
16K-374_CrAdj
16K-381_CrAdj
16K-400_CrAdj
16K-402_CrAdj
16K-405_CrAdj
16K-414_CrAdj
16K-435_CrAdj
16K-436_CrAdj
16K-439_CrAdj
16K-440_CrAdj
16K-442_CrAdj
16K-452_CrAdj
16K-456_CrAdj
16K-458_CrAdj
16K-471_CrAdj
16K-476_CrAdj
16K-493_CrAdj
16K-496_CrAdj
16K-505_CrAdj
16K-522_CrAdj
16K-577_CrAdj
16K-581_CrAdj
16K-601_CrAdj
16K-606_CrAdj
16K-615_CrAdj
16K-630_CrAdj
16K-634_CrAdj
16K-638_CrAdj
16K-642_CrAdj
16K-644_CrAdj
16K-651_CrAdj
16K-667_CrAdj
16K-678_CrAdj
16K-685_CrAdj
16K-686_CrAdj
16K-688_CrAdj
16K-695_CrAdj
16K-711_CrAdj
16K-719_CrAdj
16K-724_CrAdj
16K-725_CrAdj
16K-730_CrAdj
16K-737_CrAdj
16K-743_CrAdj
16K-755_CrAdj
16K-756_CrAdj
16K-771_CrAdj
16K-785_CrAdj
N-1_CrAdj
N-10_CrAdj
N-11_CrAdj
N-12_CrAdj
N-13_CrAdj
N-14_CrAdj
N-15_CrAdj
N-16_CrAdj
N-17_CrAdj
N-18_CrAdj
N-19_CrAdj
N-2_CrAdj
N-20_CrAdj
N-21_CrAdj
N-22_CrAdj
N-23_CrAdj
N-24_CrAdj
N-25_CrAdj
N-26_CrAdj
N-27_CrAdj
N-28_CrAdj
N-29_CrAdj
N-3_CrAdj
N-30_CrAdj
N-31_CrAdj
N-32_CrAdj
N-33_CrAdj
N-34_CrAdj
N-35_CrAdj
N-36_CrAdj
N-37_CrAdj
N-38_CrAdj
N-39_CrAdj
N-40_CrAdj
N-41_CrAdj
N-42_CrAdj
N-43_CrAdj
N-44_CrAdj
N-45_CrAdj
N-46_CrAdj
N-47_CrAdj
N-48_CrAdj
N-49_CrAdj
N-5_CrAdj
N-50_CrAdj
N-6_CrAdj
N-7_CrAdj
N-8_CrAdj
N-9_CrAdj

## Transformação da base metabolômica

A estrutura original da base metabolômica encontra-se organizada de maneira distinta da necessária para os algoritmos de aprendizado de máquina. Assim, é realizada uma transformação dos dados, reorganizando os metabólitos e amostras em um formato tabular adequado, no qual cada linha representa uma amostra e cada coluna representa um metabólito identificado.

## Seleção das colunas metabolômicas relevantes

A base metabolômica original contém informações descritivas sobre os metabólitos, como fórmula química, identificadores e outros metadados. Entretanto, para a construção do conjunto de dados utilizado em aprendizado de máquina, são necessárias apenas as variáveis correspondentes aos valores metabolômicos das amostras e o identificador de cada metabólito.

Assim, nesta etapa são selecionadas apenas a coluna de identificação dos metabólitos e as colunas referentes às amostras experimentais, identificadas pelo padrão `_CrAdj`.

In [66]:
# Identifica automaticamente as colunas das amostras
sample_cols = [c for c in metabolites.columns if "_CrAdj" in c]

# Mantém apenas o identificador do metabólito e as colunas das amostras
metabolites_ml = metabolites[
    ['metabolite_identification'] + sample_cols
]

metabolites_ml.head()

,metabolite_identification,16K-008_CrAdj,16K-021_CrAdj,16K-030_CrAdj,16K-031_CrAdj,16K-033_CrAdj,16K-070_CrAdj,16K-072_CrAdj,16K-074_CrAdj,16K-077_CrAdj,...,N-46_CrAdj,N-47_CrAdj,N-48_CrAdj,N-49_CrAdj,N-5_CrAdj,N-50_CrAdj,N-6_CrAdj,N-7_CrAdj,N-8_CrAdj,N-9_CrAdj
0,1-Methylnicotinamide,26.983984,46.237843,442.183418,270.535349,58.225953,17.991004,36.211824,21.573726,47.370384,...,62.347629,61.097004,73.359667,44.949733,323.732306,60.390361,9.809516,28.084559,245.666184,1.664852
1,2-Hydroxybutyrate,29.868686,44.531650,62.376828,71.516142,114.366679,47.601199,24.736560,129.803525,47.038833,...,5.745055,3.118573,4.635981,3.139404,9.317327,6.499133,35.379473,59.429839,32.092595,7.451337
2,2-Hydroxyisobutyrate,11.839298,19.621225,18.790962,16.755210,23.632572,20.239880,15.717092,19.743812,19.271416,...,7.970999,6.478522,8.207578,6.659892,16.081347,7.262524,7.853047,12.433092,12.205708,3.329704
3,2-Oxoisocaproate,4.837886,5.203890,4.903983,NaN,4.491258,NaN,1.384176,8.234614,3.812839,...,NaN,0.202756,1.951370,1.106958,1.478230,1.114137,4.293362,4.124602,3.840589,0.539952
4,2-Phenylpropionate,3.215241,4.265484,5.912278,10.625255,10.158798,137.931035,4.554385,9.294038,9.697874,...,1.886752,1.071708,2.944794,NaN,4.031536,2.063217,10.679058,1.329697,5.813495,4.886565

## Definição do identificador dos metabólitos

Após a seleção das variáveis relevantes, a coluna responsável pela identificação dos metabólitos é definida como índice da tabela. Essa etapa é necessária porque, posteriormente, será realizada uma reorganização estrutural dos dados, transformando metabólitos em colunas e amostras em linhas.

In [67]:
# Define o nome do metabólito como índice da tabela
metabolites_ml = metabolites_ml.set_index(
    'metabolite_identification'
)

metabolites_ml.head()

,16K-008_CrAdj,16K-021_CrAdj,16K-030_CrAdj,16K-031_CrAdj,16K-033_CrAdj,16K-070_CrAdj,16K-072_CrAdj,16K-074_CrAdj,16K-077_CrAdj,16K-092_CrAdj,...,N-46_CrAdj,N-47_CrAdj,N-48_CrAdj,N-49_CrAdj,N-5_CrAdj,N-50_CrAdj,N-6_CrAdj,N-7_CrAdj,N-8_CrAdj,N-9_CrAdj
metabolite_identification,,,,,,,,,,,,,,,,,,,,,
1-Methylnicotinamide,26.983984,46.237843,442.183418,270.535349,58.225953,17.991004,36.211824,21.573726,47.370384,302.565081,...,62.347629,61.097004,73.359667,44.949733,323.732306,60.390361,9.809516,28.084559,245.666184,1.664852
2-Hydroxybutyrate,29.868686,44.531650,62.376828,71.516142,114.366679,47.601199,24.736560,129.803525,47.038833,42.910270,...,5.745055,3.118573,4.635981,3.139404,9.317327,6.499133,35.379473,59.429839,32.092595,7.451337
2-Hydroxyisobutyrate,11.839298,19.621225,18.790962,16.755210,23.632572,20.239880,15.717092,19.743812,19.271416,24.268142,...,7.970999,6.478522,8.207578,6.659892,16.081347,7.262524,7.853047,12.433092,12.205708,3.329704
2-Oxoisocaproate,4.837886,5.203890,4.903983,NaN,4.491258,NaN,1.384176,8.234614,3.812839,5.578335,...,NaN,0.202756,1.951370,1.106958,1.478230,1.114137,4.293362,4.124602,3.840589,0.539952
2-Phenylpropionate,3.215241,4.265484,5.912278,10.625255,10.158798,137.931035,4.554385,9.294038,9.697874,8.105273,...,1.886752,1.071708,2.944794,NaN,4.031536,2.063217,10.679058,1.329697,5.813495,4.886565

## Reorganização estrutural da base metabolômica

A base metabolômica encontra-se originalmente estruturada com metabólitos organizados em linhas e amostras distribuídas em colunas. No entanto, algoritmos de aprendizado de máquina exigem uma estrutura em que cada linha represente uma amostra e cada coluna represente uma variável preditora.

Dessa forma, realiza-se a transposição da tabela, invertendo linhas e colunas.

In [68]:
# Inverte linhas e colunas da tabela
metabolites_ml = metabolites_ml.T

metabolites_ml.head()

metabolite_identification,1-Methylnicotinamide,2-Hydroxybutyrate,2-Hydroxyisobutyrate,2-Oxoisocaproate,2-Phenylpropionate,3-Hydroxyisovalerate,3-Indoxylsulfate,3-Methyl-2-oxovalerate,4-Hydroxyphenylacetate,Acetate,...,Tyramine,Urea,Valine,Xylose,cis-Aconitate,myo-Inositol,sn-Glycero-3-phosphocholine,trans-Aconitate,pi-Methylhistidine,Creatinine
16K-008_CrAdj,26.983984,29.868686,11.839298,4.837886,3.215241,2.854653,102.767511,5.468914,19.922474,22.476637,...,41.828180,5618.197662,1.953184,12.710718,57.904384,15.204784,6.009796,6.460531,107.635446,NaN
16K-021_CrAdj,46.237843,44.531650,19.621225,5.203890,4.265484,5.118580,19.365296,8.360348,9.810613,22.521754,...,41.204573,5978.075414,3.327077,8.189729,94.949667,28.749360,9.298754,8.104419,119.262924,NaN
16K-030_CrAdj,442.183418,62.376828,18.790962,4.903983,5.912278,11.916220,53.531326,7.424722,16.774371,85.109308,...,28.965580,4878.225400,4.124845,23.099134,58.114487,9.120491,8.937165,6.416426,125.532792,NaN
16K-031_CrAdj,270.535349,71.516142,16.755210,NaN,10.625255,10.216592,20.841847,8.173273,22.885166,47.404986,...,28.197793,2742.133224,6.538619,NaN,23.702493,NaN,13.485901,NaN,71.516142,NaN
16K-033_CrAdj,58.225953,114.366679,23.632572,4.491258,10.158798,13.687644,94.744159,14.703523,4.972464,142.650912,...,15.077795,7261.401914,4.918997,13.046035,42.453082,24.648452,7.111159,6.416083,111.372507,NaN

## Conversão do identificador das amostras em coluna

Após a transposição da tabela, os identificadores das amostras passam a ocupar o índice da estrutura de dados. Entretanto, para permitir a integração com a base clínica, esse índice deve ser convertido em uma coluna explícita, denominada `sample_id`.

In [69]:
# Converte o índice em coluna
metabolites_ml = metabolites_ml.reset_index()

# Renomeia a coluna de índice
metabolites_ml = metabolites_ml.rename(
    columns={'index': 'sample_id'}
)

metabolites_ml.head()

metabolite_identification,sample_id,1-Methylnicotinamide,2-Hydroxybutyrate,2-Hydroxyisobutyrate,2-Oxoisocaproate,2-Phenylpropionate,3-Hydroxyisovalerate,3-Indoxylsulfate,3-Methyl-2-oxovalerate,4-Hydroxyphenylacetate,...,Tyramine,Urea,Valine,Xylose,cis-Aconitate,myo-Inositol,sn-Glycero-3-phosphocholine,trans-Aconitate,pi-Methylhistidine,Creatinine
0,16K-008_CrAdj,26.983984,29.868686,11.839298,4.837886,3.215241,2.854653,102.767511,5.468914,19.922474,...,41.828180,5618.197662,1.953184,12.710718,57.904384,15.204784,6.009796,6.460531,107.635446,NaN
1,16K-021_CrAdj,46.237843,44.531650,19.621225,5.203890,4.265484,5.118580,19.365296,8.360348,9.810613,...,41.204573,5978.075414,3.327077,8.189729,94.949667,28.749360,9.298754,8.104419,119.262924,NaN
2,16K-030_CrAdj,442.183418,62.376828,18.790962,4.903983,5.912278,11.916220,53.531326,7.424722,16.774371,...,28.965580,4878.225400,4.124845,23.099134,58.114487,9.120491,8.937165,6.416426,125.532792,NaN
3,16K-031_CrAdj,270.535349,71.516142,16.755210,NaN,10.625255,10.216592,20.841847,8.173273,22.885166,...,28.197793,2742.133224,6.538619,NaN,23.702493,NaN,13.485901,NaN,71.516142,NaN
4,16K-033_CrAdj,58.225953,114.366679,23.632572,4.491258,10.158798,13.687644,94.744159,14.703523,4.972464,...,15.077795,7261.401914,4.918997,13.046035,42.453082,24.648452,7.111159,6.416083,111.372507,NaN

## Padronização dos identificadores das amostras

Os identificadores presentes na base metabolômica possuem o sufixo `_CrAdj`, enquanto a base clínica utiliza apenas o identificador principal da amostra. Assim, remove-se esse trecho para garantir compatibilidade entre os conjuntos de dados.

In [70]:
# Remove o sufixo '_CrAdj' dos identificadores
metabolites_ml['sample_id'] = (
    metabolites_ml['sample_id']
    .str.replace('_CrAdj', '', regex=False)
)

metabolites_ml.head()

metabolite_identification,sample_id,1-Methylnicotinamide,2-Hydroxybutyrate,2-Hydroxyisobutyrate,2-Oxoisocaproate,2-Phenylpropionate,3-Hydroxyisovalerate,3-Indoxylsulfate,3-Methyl-2-oxovalerate,4-Hydroxyphenylacetate,...,Tyramine,Urea,Valine,Xylose,cis-Aconitate,myo-Inositol,sn-Glycero-3-phosphocholine,trans-Aconitate,pi-Methylhistidine,Creatinine
0,16K-008,26.983984,29.868686,11.839298,4.837886,3.215241,2.854653,102.767511,5.468914,19.922474,...,41.828180,5618.197662,1.953184,12.710718,57.904384,15.204784,6.009796,6.460531,107.635446,NaN
1,16K-021,46.237843,44.531650,19.621225,5.203890,4.265484,5.118580,19.365296,8.360348,9.810613,...,41.204573,5978.075414,3.327077,8.189729,94.949667,28.749360,9.298754,8.104419,119.262924,NaN
2,16K-030,442.183418,62.376828,18.790962,4.903983,5.912278,11.916220,53.531326,7.424722,16.774371,...,28.965580,4878.225400,4.124845,23.099134,58.114487,9.120491,8.937165,6.416426,125.532792,NaN
3,16K-031,270.535349,71.516142,16.755210,NaN,10.625255,10.216592,20.841847,8.173273,22.885166,...,28.197793,2742.133224,6.538619,NaN,23.702493,NaN,13.485901,NaN,71.516142,NaN
4,16K-033,58.225953,114.366679,23.632572,4.491258,10.158798,13.687644,94.744159,14.703523,4.972464,...,15.077795,7261.401914,4.918997,13.046035,42.453082,24.648452,7.111159,6.416083,111.372507,NaN

## Integração das bases clínica e metabolômica

Após o pré-processamento das informações clínicas e metabolômicas, realiza-se a integração das bases utilizando o identificador único da amostra (`sample_id`). Esse procedimento permite consolidar, em uma única estrutura, tanto os atributos clínicos quanto os valores metabolômicos.

É utilizada uma junção interna (`inner join`), garantindo que apenas amostras presentes simultaneamente nas duas bases sejam mantidas no conjunto final.

In [71]:
# Integra as bases clínica e metabolômica
dataset_final = pd.merge(
    samples_clean,
    metabolites_ml,
    on="sample_id",
    how="inner"
)

print(dataset_final.shape)
dataset_final.head()

(166, 66)

,sample_id,sex,tumor_state,tumor_grade,age,neutered,er_status,her2_status,tumor_type,breed,...,Tyramine,Urea,Valine,Xylose,cis-Aconitate,myo-Inositol,sn-Glycero-3-phosphocholine,trans-Aconitate,pi-Methylhistidine,Creatinine
0,16K-008,Female,Malignant,1.0,144,Intact,Positive,Positive,simple carcinoma (grade 1),Chihuahua,...,41.828180,5618.197662,1.953184,12.710718,57.904384,15.204784,6.009796,6.460531,107.635446,NaN
1,16K-021,Female,Malignant,1.0,192,Neutered,Not Available,Not Available,NaN,Maltese,...,41.204573,5978.075414,3.327077,8.189729,94.949667,28.749360,9.298754,8.104419,119.262924,NaN
2,16K-030,Female,Malignant,1.0,156,Intact,Not Available,Not Available,NaN,Maltese,...,28.965580,4878.225400,4.124845,23.099134,58.114487,9.120491,8.937165,6.416426,125.532792,NaN
3,16K-072,Female,Malignant,2.0,144,Intact,Positive,Positive,NaN,Mixed Breed,...,16.386855,8937.220932,4.107876,9.644579,43.534560,17.369173,6.786926,8.260404,175.120557,NaN
4,16K-077,Female,Malignant,3.0,168,Intact,Negative,Negative,NaN,Beagle,...,59.016122,2439.305400,2.610966,8.744664,33.113681,7.915786,15.292801,4.558830,150.109826,NaN

In [ ]:
count = 0
for col in dataset_final.columns:
    count += 1
    print(col)

sample_id
sex
tumor_state
tumor_grade
age
neutered
er_status
her2_status
tumor_type
breed
1-Methylnicotinamide
2-Hydroxybutyrate
2-Hydroxyisobutyrate
2-Oxoisocaproate
2-Phenylpropionate
3-Hydroxyisovalerate
3-Indoxylsulfate
3-Methyl-2-oxovalerate
4-Hydroxyphenylacetate
Acetate
Acetone
Alanine
Allantoin
Betaine
Carnitine
Choline
Citrate
Creatine
Dimethylamine
Formate
Fumarate
Glucose
Glycerol
Glycine
Guanidoacetate
Hippurate
Histidine
Isoleucine
Isopropanol
Kynurenate
Lactate
Mannose
Methanol
Methylamine
Methylguanidine
N,N-Dimethylglycine
N-Phenylacetylglycine
O-Phosphocholine
Propylene glycol
Pyruvate
Succinate
Taurine
Threonine
Trigonelline
Trimethylamine
Tryptophan
Tyramine
Urea
Valine
Xylose
cis-Aconitate
myo-Inositol
sn-Glycero-3-phosphocholine
trans-Aconitate
pi-Methylhistidine
Creatinine
Número total de colunas: 66

In [74]:
print(f"Número total de colunas: {count}")

Número total de colunas: 66

In [76]:
dataset_final.shape

(166, 66)

In [77]:
dataset_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 66 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   sample_id                    166 non-null    str
 1   sex                          166 non-null    str
 2   tumor_state                  166 non-null    str
 3   tumor_grade                  94 non-null     float64
 4   age                          166 non-null    str
 5   neutered                     166 non-null    str
 6   er_status                    117 non-null    str
 7   her2_status                  117 non-null    str
 8   tumor_type                   52 non-null     str
 9   breed                        166 non-null    str
 10  1-Methylnicotinamide         165 non-null    float64
 11  2-Hydroxybutyrate            164 non-null    float64
 12  2-Hydroxyisobutyrate         166 non-null    float64
 13  2-Oxoisocaproate             150 non-null    float64
 14  2-Phenylpropionate           159 non-null    float64
 15  3-Hydroxyisovalerate         164 non-null    float64
 16  3-Indoxylsulfate             154 non-null    float64
 17  3-Methyl-2-oxovalerate       154 non-null    float64
 18  4-Hydroxyphenylacetate       162 non-null    float64
 19  Acetate                      165 non-null    float64
 20  Acetone                      159 non-null    float64
 21  Alanine                      165 non-null    float64
 22  Allantoin                    166 non-null    float64
 23  Betaine                      163 non-null    float64
 24  Carnitine                    165 non-null    float64
 25  Choline                      165 non-null    float64
 26  Citrate                      118 non-null    float64
 27  Creatine                     165 non-null    float64
 28  Dimethylamine                166 non-null    float64
 29  Formate                      164 non-null    float64
 30  Fumarate                     113 non-null    float64
 31  Glucose                      165 non-null    float64
 32  Glycerol                     156 non-null    float64
 33  Glycine                      157 non-null    float64
 34  Guanidoacetate               149 non-null    float64
 35  Hippurate                    165 non-null    float64
 36  Histidine                    163 non-null    float64
 37  Isoleucine                   157 non-null    float64
 38  Isopropanol                  165 non-null    float64
 39  Kynurenate                   164 non-null    float64
 40  Lactate                      166 non-null    float64
 41  Mannose                      147 non-null    float64
 42  Methanol                     159 non-null    float64
 43  Methylamine                  165 non-null    float64
 44  Methylguanidine              162 non-null    float64
 45  N,N-Dimethylglycine          163 non-null    float64
 46  N-Phenylacetylglycine        164 non-null    float64
 47  O-Phosphocholine             154 non-null    float64
 48  Propylene glycol             166 non-null    float64
 49  Pyruvate                     166 non-null    float64
 50  Succinate                    166 non-null    float64
 51  Taurine                      164 non-null    float64
 52  Threonine                    162 non-null    float64
 53  Trigonelline                 130 non-null    float64
 54  Trimethylamine               165 non-null    float64
 55  Tryptophan                   152 non-null    float64
 56  Tyramine                     162 non-null    float64
 57  Urea                         166 non-null    float64
 58  Valine                       165 non-null    float64
 59  Xylose                       157 non-null    float64
 60  cis-Aconitate                164 non-null    float64
 61  myo-Inositol                 150 non-null    float64
 62  sn-Glycero-3-phosphocholine  164 non-null    float64
 63  trans-Aconitate              160 non-null    float64
 64  pi-Methylhistidine           166 non-null    float64
 65  Creatinine                   0 non-null      float64
dtypes: float64(57), str(9)
memory usage: 85.7 KB

In [78]:
dataset_final.isnull().sum().sort_values(ascending=False)

Creatinine            166
tumor_type            114
tumor_grade            72
Fumarate               53
her2_status            49
                     ...
Propylene glycol        0
Pyruvate                0
Succinate               0
Urea                    0
pi-Methylhistidine      0
Length: 66, dtype: int64

In [84]:
dataset_final = dataset_final.drop(columns=['Creatinine'])

In [80]:
dataset_final['tumor_state'].value_counts()

tumor_state
Malignant        94
Control Group    49
Benign           23
Name: count, dtype: int64

In [83]:
dataset_final['tumor_grade'].value_counts()

tumor_grade
1.0    53
3.0    21
2.0    20
Name: count, dtype: int64

In [81]:
dataset_final['age'].unique()[:20]

<StringArray>
[          '144',           '192',           '156',           '168',
           '180',            '72',           '108', 'Not Available',
           '132',            '84',           '120',            '96',
            '24',           '204',           '228',           '107',
            '60',            '48',             '9',             '6']
Length: 20, dtype: str

In [82]:
dataset_final['age'] = pd.to_numeric(
    dataset_final['age'],
    errors='coerce'
)